hydra:
  searchpath:
    - file://verl-0.6.0/verl/trainer/config

defaults:
  - ppo_trainer
  - _self_
  
actor_rollout_ref:
  actor:
    _target_: GVPO.gvpo_actor_config.FSDPActorConfig
    gvpo_beta: 0.1
  
trainer:
  project_name: gvpo